apiVersion: apps/v1
kind: Deployment
metadata:
  name: occ-seeder
  namespace: occ
spec:
  selector:
    matchLabels:
      name: occ-seeder
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: occ-seeder
    spec:
      imagePullSecrets:
        - name: secret
      containers:
        - name: occ-seeder
          image: seeder:IMAGE_TAG
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
