version: "3"
services:
  occ-mongo:
    container_name: occ-mongo
    image: mongo
    ports:
      - "27017:27017"

  occ-redis:
    container_name: occ-redis
    image: redis
    ports:
      - "6379:6379"

  occ-api:
    container_name: occ-api
    image: api
    ports:
      - "3333:3333"
    links:
      - occ-mongo
    depends_on:
      - occ-mongo

  occ-worker:
    container_name: occ-worker
    image: worker
    ports:
      - "3500:3500"
    command: ["node", "server.js"]
    links:
      - occ-mongo
      - occ-redis
    depends_on:
      - occ-mongo
      - occ-redis
      - occ-api

  occ-mailserver:
    container_name: occ-mailserver
    image: mailserver
    ports:
      - "3800:3800"
