apiVersion: v1
kind: Service
metadata:
  name: occ-worker
  namespace: occ
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3500
  selector:
    name: occ-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: occ-worker
  namespace: occ
spec:
  selector:
    matchLabels:
      name: occ-worker
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  replicas: 2
  template:
    metadata:
      labels:
        name: occ-worker
    spec:
      imagePullSecrets:
        - name: secret
      containers:
        - name: occ-worker
          image: worker:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          command: ['node']
          args: ['server.js']
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1
              port: 3500
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1
              port: 3500
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            requests:
              memory: '512Mi'
              cpu: '1000m'
            limits:
              memory: '1024Mi'
              cpu: '2000m'
